version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: gymsmart
      POSTGRES_PASSWORD: gymsmartpass
      POSTGRES_DB: gymsmartdb
    ports:
       - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: