version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5433:5432

    environment:
     - POSTGRESQL_USERNAME=gore
     - POSTGRESQL_PASSWORD=gore
     - POSTGRES_DATABASE=apisolid